on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  build-standalone:
    runs-on: ubuntu-latest
    container: debian:bookworm
    steps:
      - run: apt update
      
      - name: Install dependencies
        run: >
          apt install -y
          git
          python3
          python-is-python3
          gettext
          intltool
          g++
          pkgconf
          libsndfile1-dev
          libfftw3-dev
          libjack-jackd2-dev
          libglib2.0-dev
          libcurl4-openssl-dev
          sassc
          libgtkmm-3.0-dev
          liblrdf0-dev
          liblilv-dev
          libboost-system-dev
          libboost-iostreams-dev
          libeigen3-dev
      
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          
      - name: Build
        run: |
          cd trunk
          ./waf configure --prefix=/usr --no-avahi --no-bluez --no-nsm --includeresampler --includeconvolver --optimization
          ./waf build
