on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  build-standalone:
    runs-on: ubuntu-latest
    container: debian:bookworm
    steps:
      - run: apt update
      - run: apt upgrade -y git
      
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      
      - name: Install dependencies
        run: >
          apt install -y
          build-essential
          
      - name: Build
        run: |
          cd trunk
          ./waf configure --prefix=/usr --includeresampler --includeconvolver --optimization
          ./waf build
